### ISSUE TITLE
Downloaded the framework, installed and tested but getting an error

### ISSUE THREAD

**Issue by l1ndener** [wmaop/wm-aop#2]
Morning,

Having followed your guide, when either I try to verify, or use jcode to rebuild the classes it seems that there are missing classes. 

For example in the invokemanager it refers to chainprocessor package, also in the build it refers to the flow package, none of these are present in the OrgWmAOP-1 package.

Any assistance appreciated with this.

Many thanks and kind regards

**Comment by sysgen** [comment]
Which versions are you using of wm-aop and OrgWmAOP?  There's a revised
version of the OrgWmAop package (1.0.2) that has the class names updated.
Can you try that version?

Let me know if you have further problems or need clarification on use, etc.

You can contact me directly on richard@sysgen.co.uk

Regards

Richard

**Comment by sysgen** [comment]
Appears to be an issue with the compiled version of the classes in the package - They've been compiled for JSE8 but require JSE7 for 9.7 and earlier.  Will updated all packages on earlier wM release to make fully 9.x compliant.

**Comment by l1ndener** [comment]
Hi Richard,

Many thanks for the time and trouble.

I will keep an eye on the pages.

Kind regards,
Lawrence

On 26 May 2016, at 18:34, Richard Tomlinson <notifications@github.com<mailto:notifications@github.com>> wrote:

Appears to be an issue with the compiled version of the classes in the package - They've been compiled for JSE8 but require JSE7 for 9.7 and earlier. Will updated all packages on earlier wM release to make fully 9.x compliant.

—
You are receiving this because you authored the thread.
Reply to this email directly or view it on GitHubhttps://github.com/wmaop/wm-aop/issues/2#issuecomment-221940226
- This electronic document (comprising text and any attachments) is confidential and intended solely for the use of the individual or entity to whom it is addressed.
- P&O Ferries Holdings Ltd disclaims all legal responsibility for the accuracy or otherwise of any information contained within this electronic document (comprising text and any attachments).
- Any view expressed about individuals or other companies is that of the originator of the document and in no way represents the corporate view of P&O Ferries Holdings Ltd.
- P&O Ferries Holdings Limited is registered in England and Wales under company number 6038077. Registered office is Channel House, Channel View Road, Dover, Kent CT17 9TJ.
- This footnote also confirms that the document has been swept by MIMEsweeper for the presence of computer viruses.
- www.poferries.com

**Comment by sysgen** [comment]
Updated OrgWmAOP to 1.0.3 which now works ok on all versions.
